#!/bin/sh
set -eu

TPROXY_MARK="${TPROXY_MARK:-0x1/0x1}"
TPROXY_TABLE="${TPROXY_TABLE:-100}"
ROUTING_MODE="${ROUTING_MODE:-tproxy}"
INBOUND_INTERFACE="${INBOUND_INTERFACE:-}"
TUN_INTERFACE="${TUN_INTERFACE:-xray0}"
TUN_TABLE="${TUN_TABLE:-100}"
TUN_PRIORITY="${TUN_PRIORITY:-1000}"
TUN_SOCKS_PRIORITY="${TUN_SOCKS_PRIORITY:-900}"
TUN_LOCAL_PRIORITY="${TUN_LOCAL_PRIORITY:-950}"
ENABLE_SOCKS="${ENABLE_SOCKS:-1}"
SOCKS_PORT="${SOCKS_PORT:-1080}"
SOCKS_ROUTE_MARK="${SOCKS_ROUTE_MARK:-0x2/0x2}"
SOCKS_ROUTE_TABLE="${SOCKS_ROUTE_TABLE:-200}"
SOCKS_VRF="${SOCKS_VRF:-socksvrf}"

if [ -r /run/xray-socks5-router/runtime.env ]; then
  # Values are generated by the entrypoint from validated interface names and integers.
  # shellcheck disable=SC1091
  . /run/xray-socks5-router/runtime.env
fi

xray_pid="$(pidof xray)"
xray_uid="$(id -u xray)"
awk -v expected="$xray_uid" \
  '$1 == "Uid:" { exit($2 == expected ? 0 : 1) }' "/proc/${xray_pid}/status"

case "$ROUTING_MODE" in
  tproxy)
    ip -4 rule show | \
      grep -F "fwmark ${TPROXY_MARK} lookup ${TPROXY_TABLE}" >/dev/null
    ;;
  tun)
    ip link show dev "$TUN_INTERFACE" >/dev/null
    ip -4 rule show priority "$TUN_PRIORITY" | \
      grep -F "iif ${INBOUND_INTERFACE} lookup ${TUN_TABLE}" >/dev/null
    ip -4 route show table "$TUN_TABLE" | \
      grep -F "default dev ${TUN_INTERFACE}" >/dev/null
    ip -4 rule show priority "$TUN_LOCAL_PRIORITY" | \
      grep -F "not from all uidrange ${xray_uid}-${xray_uid} lookup ${TUN_TABLE}" >/dev/null
    ;;
  *) exit 1 ;;
esac

if [ "$ENABLE_SOCKS" = "1" ]; then
  pidof hev-socks5-server >/dev/null
  ss -lnt | grep -E "[:.]${SOCKS_PORT}[[:space:]]" >/dev/null
  if [ "$ROUTING_MODE" = "tun" ]; then
    socks_uid="$(id -u socks)"
    ip -4 rule show priority "$TUN_SOCKS_PRIORITY" | \
      grep -F "uidrange ${socks_uid}-${socks_uid} lookup ${SOCKS_ROUTE_TABLE}" >/dev/null
    ip -4 route show table "$SOCKS_ROUTE_TABLE" | \
      grep -F "default dev ${TUN_INTERFACE}" >/dev/null
  else
    ip link show "$SOCKS_VRF" >/dev/null
    ip -4 rule show | \
      grep -F "fwmark ${SOCKS_ROUTE_MARK} lookup ${SOCKS_ROUTE_TABLE}" >/dev/null
  fi
fi
